name: Security Analysis

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  security_checks:
    runs-on: ubuntu-latest
    
    steps:
      - name: Step 1 - Checkout code
        uses: actions/checkout@v4

      - name: Step 2 - Run CodeQL Analysis
        uses: github/codeql-action/init@v3
        with:
          queries: security-and-quality
          languages: python

      - name: Step 3 - Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

      - name: Step 4 - Dependency Review
        if: github.event_name == 'pull_request'
        uses: actions/dependency-review-action@v4
        with:
          base_ref: ${{ github.event.pull_request.base.ref }}
          head_ref: ${{ github.event.pull_request.head.ref }}
